const FILTER_BRANDS = "FILTER_BRANDS";
const FILTER_COLORS = "FILTER_COLORS";
const CLEAR_FILTERS = "CLEAR_FILTERS";
const LOW_TO_HIGH = "LOW_TO_HIGH";
const HIGH_TO_LOW = "HIGH_TO_LOW";
const FILTER_GENDER = "FILTER_GENDER";
const FILTER_SEARCH = "FILTER_SEARCH";
const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const CHANGE_CART_QTY = "CHANGE_CART_QTY";
const GET_SIMILAR_PRODUCTS = "GET_SIMILAR_PRODUCTS";

export {
  FILTER_BRANDS,
  FILTER_COLORS,
  CLEAR_FILTERS,
  LOW_TO_HIGH,
  HIGH_TO_LOW,
  FILTER_GENDER,
  FILTER_SEARCH,
  ADD_TO_WISHLIST,
  REMOVE_FROM_WISHLIST,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  CHANGE_CART_QTY,
  GET_SIMILAR_PRODUCTS,
};
